definitions:
  userservice_api.infoResponse:
    properties:
      bio:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  userservice_api.registerRequest:
    properties:
      bio:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  userservice_api.registerResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/users/get_info:
    get:
      description: Returns information about a user by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userservice_api.infoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about user
      tags:
      - users
  /api/v1/users/register:
    post:
      consumes:
      - application/json
      description: Creates a new user in system
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/userservice_api.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/userservice_api.registerResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User registration
      tags:
      - users
swagger: "2.0"
