definitions:
  auth_api.loginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth_api.loginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  auth_api.refreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  auth_api.refreshResponse:
    properties:
      access_token:
        type: string
    type: object
  auth_api.validateRequest:
    properties:
      access_token:
        type: string
    type: object
  auth_api.validateResponse:
    properties:
      username:
        type: string
    type: object
  message_api.msgRequest:
    properties:
      content:
        type: string
      receiver_id:
        type: string
    required:
    - content
    - receiver_id
    type: object
  message_api.msgResponse:
    properties:
      message:
        type: string
    type: object
  message_api.sendRequest:
    properties:
      content:
        type: string
    required:
    - content
    type: object
  message_api.sendResponse:
    properties:
      message:
        type: string
    type: object
  user_api.deleteResponse:
    properties:
      message:
        type: string
    type: object
  user_api.infoResponse:
    properties:
      bio:
        type: string
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  user_api.paginationMeta:
    properties:
      has_next:
        type: boolean
      has_prev:
        type: boolean
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  user_api.registerRequest:
    properties:
      bio:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  user_api.registerResponse:
    properties:
      message:
        type: string
    type: object
  user_api.usernameData:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
  user_api.usernamesListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/user_api.usernameData'
        type: array
      meta:
        $ref: '#/definitions/user_api.paginationMeta'
    type: object
info:
  contact: {}
  title: Cosmo Messenger API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates user and returns JWT tokens
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth_api.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth_api.loginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Returns new access token by refresh token
      parameters:
      - description: Refresh credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth_api.refreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth_api.refreshResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User refresh token
      tags:
      - auth
  /api/v1/auth/validate:
    post:
      consumes:
      - application/json
      description: Returns userID if access token is valid
      parameters:
      - description: Access credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth_api.validateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth_api.validateResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Validates users access token
      tags:
      - auth
  /api/v1/chats:
    get:
      consumes:
      - application/json
      description: Get paginated list of user's chats
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of chats per page
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user chats
      tags:
      - chats
  /api/v1/messages/chat/{chat_id}:
    get:
      consumes:
      - application/json
      description: Get paginated messages from a chat
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: string
      - description: Cursor Message ID
        in: query
        name: cursor
        type: string
      - default: '"older"'
        description: Scrolling direction
        in: query
        name: dir
        type: string
      - default: 10
        description: Number of messages per page
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Access denied to chat
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Chat not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get chat messages
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Send message
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: string
      - description: Message data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/message_api.sendRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/message_api.sendResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Message sending
      tags:
      - messages
  /api/v1/messages/direct:
    post:
      consumes:
      - application/json
      description: Send direct message
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/message_api.msgRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/message_api.msgResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Message sending
      tags:
      - messages
  /api/v1/users/delete:
    delete:
      consumes:
      - application/json
      description: Deletes the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_api.deleteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete current user
      tags:
      - users
  /api/v1/users/delete/{user_id}:
    delete:
      consumes:
      - application/json
      description: Deletes a user by id. Admin access required.
      parameters:
      - description: Username of the user to delete
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_api.deleteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete user by id (Admin only)
      tags:
      - users
  /api/v1/users/get_info:
    get:
      description: Returns information about a user by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_api.infoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about user
      tags:
      - users
  /api/v1/users/get_usernames_list:
    get:
      consumes:
      - application/json
      description: Returns paginated usernames list
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_api.usernamesListResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get usernames list
      tags:
      - users
  /api/v1/users/register:
    post:
      consumes:
      - application/json
      description: Creates a new user in system
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user_api.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user_api.registerResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User registration
      tags:
      - users
  /ws:
    get:
      description: WebSocket endpoint for real-time messaging
      responses: {}
      summary: WebSocket connection for real-time messages
      tags:
      - websocket
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
